### ISSUE TITLE
app crashes when attempting to load any q_4_0_4_8 model

### ISSUE THREAD

**Issue by lilyanatia** [a-ghorbani/pocketpal-ai#50] opened 2024-10-11 17:20 UTC
attempting to load any q4_0_4_8 model crashes PocketPal. q4_0_4_4 works, but q4_0_4_8 should be faster on devices that support i8mm.
[pocketpal.log](https://github.com/user-attachments/files/17345742/pocketpal.log)

**Comment by zchdoc** [comment] 2024-10-12 05:09
me too

**Comment by larsjuhljensen** [comment] 2024-10-24 19:44
I have the same problem on my Pixel 8a.

**Comment by a-ghorbani** [comment] 2024-11-03 07:41
Hey, I’ve just released version **1.4.5** (#72). Please give it a spin and let me know here if the issue persists.

**Comment by zchdoc** [comment] 2024-11-03 09:36
> Hey, I’ve just released version **1.4.5** (#72). Please give it a spin and let me know here if the issue persists.

![Screenshot_2024-11-03-16-34-15-518_com.pocketpalai.jpg](https://github.com/user-attachments/assets/19c866b0-203d-4d32-a21a-e22a707de3d7)

**Comment by a-ghorbani** [comment] 2024-11-03 09:53
@lilyanatia, it seems the issue is resolved now. I’m closing this for now, but if you face any crashes, feel free to open a new one.

**Closed by a-ghorbani** 2024-11-03 09:53 UTC
